name = "arch"
license = "ISC"
licenselink = "https://github.com/ryanburnette/arch/blob/master/LICENSE"
description = ""
homepage = "https://github.com.com/ryanburnette/arch"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Ryan Burnette"
  homepage = "https://ryanburnette.com"
