name = "arc"
license = "ISC"
licenselink = "https://git.ryanburnette.com/ryanburnette/arc/src/branch/master/LICENSE"
description = "Arc needs no description."
homepage = "https://git.ryanburnette.com/ryanburnette/arc"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Ryan Burnette"
  homepage = "https://ryanburnette.com"
