name = "Ryan Burnette"
license = "ISC"
licenselink = "https://github.com/ryanburnette/hugo-theme/blob/master/LICENSE"
description = ""
homepage = "https://github.com.com/ryanburnette/hugo-theme"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Ryan Burnette"
  homepage = "https://ryanburnette.com"
