name = "eon"
license = "ISC"
licenselink = "https://github.com/ryanburnette/eon/src/branch/master/LICENSE"
description = "Eon is a Hugo theme and custom Bulma implementation for building websites."
homepage = "https://github.com/ryanburnette/eon"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Ryan Burnette"
  homepage = "https://ryanburnette.com"
